### ISSUE TITLE
TypeError: socketio.listen is not a function

### ISSUE THREAD

**Issue by windowshopr** [floatinghotpot/casino-server#40]
```
PS C:\Users\chalu\OneDrive\Desktop\casino_server> node bin/casino-server
C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\index.js:602
                throw err;
                ^

TypeError: socketio.listen is not a function
    at LoginServer.startInstance (C:\Users\chalu\OneDrive\Desktop\casino_server\lib\login_server.js:76:30)
    at C:\Users\chalu\OneDrive\Desktop\casino_server\lib\login_server.js:150:10
    at try_callback (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\index.js:592:9)
    at RedisClient.return_reply (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\index.js:685:13)
    at ReplyParser.<anonymous> (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\index.js:321:14)
    at ReplyParser.emit (node:events:513:28)
    at ReplyParser.send_reply (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\lib\parser\javascript.js:300:10)
    at ReplyParser.execute (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\lib\parser\javascript.js:189:22)
    at RedisClient.on_data (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\index.js:547:27)
    at Socket.<anonymous> (C:\Users\chalu\OneDrive\Desktop\casino_server\node_modules\redis\index.js:102:14)
```

**Comment by windowshopr** [comment]
It was because the package.json says:

```
    "socket.io": "^1.2.1",
    "socket.io-redis": "^0.1.4"
```

Because these are old versions, you'll run into this issue. Take out both `^`'s before you run `npm install` and you're good.
